name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Testing compiler
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use the version your app targets

    - name: Restore dependencies
      run: dotnet restore

    - name: Build app
      run: dotnet build --no-restore

    - name: Run the web app
      run: |
        dotnet run --project ./FoodDeliveryBackend.csproj --urls http://localhost:5000 &
        sleep 6

    - name: Send test request
      shell: pwsh
      run: |
        $response = Invoke-WebRequest -Uri http://localhost:5000/api/weather/latest -UseBasicParsing
        Write-Output "Status Code: $($response.StatusCode)"
        
        if ($response.StatusCode -ne 200) {
          Write-Error "Expected HTTP 200 but got $($response.StatusCode)"
          exit 1
        }
