name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Testing compiler
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use the version your app targets

    - name: Restore dependencies
      run: dotnet restore

    - name: Build app
      run: dotnet build --no-restore

    - name: Run the web and send test GET request.
      shell: pwsh
      run: |
        $job = Start-Job { dotnet run --project ./FoodDeliveryBackend.csproj --urls http://localhost:5000 }
        
        # Wait until the app is ready
        $maxRetries = 10
        $delay = 2
        for ($i = 0; $i -lt $maxRetries; $i++) {
          try {
            Invoke-WebRequest -Uri http://localhost:5000/api/weather/latest -UseBasicParsing -TimeoutSec 2
            Write-Host "Server is ready!"
            break
          } catch {
            Write-Host "Waiting for server to start... ($i/$maxRetries)"
            Start-Sleep -Seconds $delay
          }
        }

        if ($i -eq $maxRetries) {
          Write-Error "Server did not start in time"
          exit 1
        }
        
        # Actual test
        $response = Invoke-WebRequest -Uri http://localhost:5000/api/weather/latest -UseBasicParsing
        Write-Host "Status Code: $($response.StatusCode)"
        
        if ($response.StatusCode -ne 200) {
          Write-Error "Expected HTTP 200 but got $($response.StatusCode)"
          exit 1
        }

        # Clean up
        Stop-Job $job
